name: Development Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  development_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit-Tests
        run: npm run test

      # Install Playwright for end-to-end tests
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps

      # Run e2e-tests
      # - name: Run E2E-Tests
      #   run: npm run test:e2e

      # deploy the application to some hosting platform - deployment not yet implemented
      # - name: Trigger Deployment
      #   if: ${{ github.event_name == 'push' }}
      #   run: curl
