name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: financial_dashboard_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Seed Test Database
        run: npm run seed
        env:
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/financial_dashboard_test?sslmode=disable
          AUTH_SECRET: test-secret-do-not-use-in-production

      - name: Build production version
        run: npm run build
        env:
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/financial_dashboard_test?sslmode=disable
          AUTH_SECRET: test-secret-do-not-use-in-production

      - name: Run Unit-Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E-Tests
        run: npm run test:e2e
        env:
          POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/financial_dashboard_test?sslmode=disable
          AUTH_SECRET: test-secret-do-not-use-in-production
